(()=>{
'use strict';
const labels={all:'すべて',new_store:'新店舗',limited_menu:'期間限定メニュー・フェア',event:'イベント',new_product:'新商品',sale_campaign:'セール・キャンペーン'};
const icons={new_store:'🆕',limited_menu:'⭐',event:'🎪',new_product:'🛍️',sale_campaign:'🏷️'};
const dayMs=86400000;
const isoToday=()=>new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Tokyo'})).toISOString().slice(0,10);
const daysLeft=end=>end?Math.ceil((new Date(end+'T23:59:59+09:00')-new Date())/dayMs):null;
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
function normalizedDiscoveries(list){return list.map(x=>({id:x.id,type:'new_store',title:x.title,place:x.area||x.region,summary:x.summary,startDate:x.openDate,endDate:x.expiresAt,region:x.region,emoji:x.emoji||icons.new_store,url:x.url,verifiedByOfficial:!!x.verifiedByOfficial,verificationLabel:x.verificationLabel||'情報源を確認'}));}
function embeddedEvents(){try{const raw=document.querySelector('#munakata-data')?.textContent;if(!raw)return[];const data=JSON.parse(raw);return (data.events||[]).map(x=>({id:'embedded-'+x.id,type:'event',title:x.title,place:x.location||x.place||'宗像市内',summary:x.summary||x.description||'開催内容は公式情報で確認してください。',startDate:x.startDate||x.date,endDate:x.endDate||x.startDate||x.date,region:x.region||'宗像市内',emoji:x.emoji||icons.event,url:x.url,verifiedByOfficial:true,verificationLabel:'掲載元で確認'}));}catch(error){console.warn('イベントデータを読み込めませんでした',error);return[]}}
function remaining(item){const n=daysLeft(item.endDate);if(n===null)return'';if(n<0)return'終了';if(n===0)return'今日まで';if(n<=7)return`あと${n}日`;return`${item.endDate.replaceAll('-','/')}まで`;}
function makeCard(item){const card=el('article','lh-card');const top=el('div','lh-top');top.append(el('span','lh-icon',item.emoji||icons[item.type]),el('span','lh-type',labels[item.type]));card.append(top,el('h3','',item.title));if(item.place)card.append(el('div','lh-place',item.place));card.append(el('p','lh-summary',item.summary||'詳細は掲載元で確認してください。'));const meta=el('div','lh-meta');if(item.region)meta.append(el('span','lh-chip',item.region));const remain=remaining(item);if(remain)meta.append(el('span','lh-chip '+((daysLeft(item.endDate)??99)<=7?'lh-ending':''),remain));card.append(meta);const actions=el('div','lh-actions');const check=el('span','lh-check',item.verificationLabel||(item.verifiedByOfficial?'公式確認済み':'追加確認中'));if(item.url){const link=el('a','', '詳しく見る');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';actions.append(link)}actions.append(check);card.append(actions);return card}
async function init(){const mount=el('section');mount.id='local-highlights';const wrap=el('div','lh-wrap');const head=el('div','lh-head');const titles=el('div');titles.append(el('h2','', '宗像の「今」を見つける'),el('p','lh-sub','新店舗だけでなく、期間限定・新商品・お得情報まで。'));head.append(titles);const tabs=el('div','lh-tabs');tabs.setAttribute('role','group');tabs.setAttribute('aria-label','情報の種類');const grid=el('div','lh-grid');wrap.append(head,tabs,grid);mount.append(wrap);document.body.prepend(mount);
let offers=[],discoveries=[];try{[offers,discoveries]=await Promise.all([fetch('offers.json?v=20260723',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('offers');return r.json()}),fetch('discoveries.json?v=20260723',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('discoveries');return r.json()})])}catch(error){console.error('地域情報の読み込みに失敗しました',error)}
const byId=new Map();[...normalizedDiscoveries(discoveries),...embeddedEvents(),...offers].forEach(item=>byId.set(item.id,item));const today=isoToday();const items=[...byId.values()].filter(x=>!x.endDate||x.endDate>=today).sort((a,b)=>(a.endDate||'9999').localeCompare(b.endDate||'9999'));
let current='all';function render(){grid.replaceChildren();const selected=current==='all'?items:items.filter(x=>x.type===current);if(!selected.length)grid.append(el('div','lh-empty','現在掲載できる情報はありません。確認でき次第追加します。'));else selected.forEach(x=>grid.append(makeCard(x)));[...tabs.children].forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.type===current)))}
Object.entries(labels).forEach(([type,label])=>{const button=el('button','',label);button.type='button';button.dataset.type=type;button.addEventListener('click',()=>{current=type;render()});tabs.append(button)});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
